# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 748506a81e06aca75240787e75df61858913083cabf0f9646e43e03b0299403e88be13e0d89606dc6bb0e347218e7af70b14a0681978d2f04047224bc41b5ae9

test:
  secret_key_base: b64c9edc40064f9362a3066f8794cda16b0381f5ad1d77ac7ae82df1b7b4db00157c70da5f619b46f0e57e5b39a0d9a361dccf1e3fb34d09c2d723a1f7bd953a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
